// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { PlasmicSignup } from "../components/plasmic/ratecare/PlasmicSignup";
import { useRouter } from "next/router";
import enforceUnAuth from "../utils/enforceUnAuth";

function Signup() {

  return (
    <ph.PageParamsProvider params={useRouter().query} query={useRouter().query}>
      <PlasmicSignup />
    </ph.PageParamsProvider>
  );
}

export const getServerSideProps = enforceUnAuth();

export default Signup;
